name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  tl_getx_router_gen_annotations: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  tl_getx_router_generator: any
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

dependency_overrides:
  tl_getx_router_gen_annotations:
    path: ../../tl_getx_router_gen_annotations
  tl_getx_router_generator:
    path: ../
  get:
    path: D:\Code\getx

flutter:

  uses-material-design: true
