name: tl_getx_router_generator
description: tl_getx 注解路由生成器
version: 1.0.0
homepage: https://github.com/SakurasDuck

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^5.0.0
  build: ^2.3.1
  code_builder: ^4.5.0
  collection: ^1.16.0
  dart_style: ^2.2.4
  glob: ^2.1.1
  path: ^1.8.2
  source_gen: ^1.2.6
  tl_getx_router_gen_annotations: ^1.0.0
  built_collection: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

