name: tl_getx_router_gen_annotations
description: GetX Router Generator Annotations
version: 1.0.0
homepage: https://github.com/SakurasDuck

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  
  